version: "3"
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=ebook_repository
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "33006:3306"
    backbone:
        build:  ./backbone
        command: >
            sh -c "python backbone/manage.py wait_for_db &&
                   python backbone/manage.py migrate &&
                   python backbone/manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/backbone
        depends_on:
            - db
    search:
        build: ./search
        ports:
            - "5000:5000"
        command:
            sh -c "flask run --host=0.0.0.0 --port=5000"
            
            
